<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HolyGift\HolyGift.csproj" />
    <ProjectReference Include="..\ILogger\ILogger.csproj" />
    <ProjectReference Include="..\Judgment\Judgment.csproj" />
  </ItemGroup>

</Project>
